# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
pan1:
  ID: 6
  Return_Delay_Time: 0
pan2:
  ID: 9
  Return_Delay_Time: 0


tilt1:
  ID: 18
  Return_Delay_Time: 0
tilt2:
  ID: 14
  Return_Delay_Time: 0
